name: Run api with cleanup

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  NEW_POLLSTER_DISCORD_WEBHOOK: ${{ secrets.NEW_POLLSTER_DISCORD_WEBHOOK }}

jobs:
  publish:
    permissions:
      contents: write
    name: Update API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - name: Validate config
        run: node src/validateConfigs.js
      - name: Run Index
        run: node src/index.js
      - name: Check if index.json exists
        if: ${{ hashFiles('output/v1/index.json') == '' }}
        run: exit 1
      - name: Check if parties.json exists
        if: ${{ hashFiles('output/v1/parties.json') == '' }}
        run: exit 1
      - name: Check if pollsters.json exists
        if: ${{ hashFiles('output/v1/pollsters.json') == '' }}
        run: exit 1
      - name: Check if only dateModified has changed
        id: check_date_modified
        run: |
          cd output
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --name-only > changed_files.txt

          # Check if all changes are only in dateModified
          only_date_modified=true
          while IFS= read -r file; do
            if [[ -f "$file" ]]; then
              # Check if the file has changes other than dateModified
              if git diff --staged "$file" | grep -v '"dateModified":' | grep -E '^\+|^\-' > /dev/null; then
                only_date_modified=false
                break
              fi
            fi
          done < changed_files.txt

          echo "only_date_modified=$only_date_modified" >> $GITHUB_OUTPUT
          rm -rf .git

      - name: Push API changes
        if: steps.check_date_modified.outputs.only_date_modified != 'true'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: api
          FOLDER: output
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Update API: last api changes ({sha})"
          SKIP_EMPTY_COMMITS: true
